env:
  global:
    - CC_TEST_REPORTER_ID=5cea74285558a23f091a5586da12930ec1d701781670ad6730fa383eb06a6aa0
    - SECRETKEY=automart1234455
    - NODE_ENV=test
    - PGTEST_URL=postgres://xextnteg:fCNLK30hKJMQCIqmAi65-Fu-cKV5mC09@raja.db.elephantsql.com:5432/xextnteg

language: node_js

node_js:
  - '8.11.3'

sudo: false

services:
  - postgresql

install:
  - npm install -q --no-color --no-progress

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
    - nyc --reporter=lcov npm run test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coverage
